import type { Product, ScrapeLog, Watchlist } from "@/types/domain";

export const stores = [
  { key: "homepro", name: "HomePro" },
  { key: "powerbuy", name: "Power Buy" },
  { key: "advice", name: "Advice" },
  { key: "jib", name: "JIB" },
];

export const products: Product[] = [
  {
    id: "prd-1",
    title: 'LG UltraGear 27" QHD Gaming Monitor',
    store: "Power Buy",
    storeKey: "powerbuy",
    category: "Monitor",
    imageUrl: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
    sourceUrl: "https://www.powerbuy.co.th/th/product/lg-ultragear-27gr75q-b-gaming-monitor",
    currentPrice: 8990,
    targetPrice: 8500,
    lowest30d: 8590,
    average30d: 9690,
    lastCheckedAt: "2026-06-11T12:05:00+07:00",
    status: "IN_STOCK",
    confidenceLevel: "HIGH",
    confidenceLabel: "จับคู่แบบมีโครงสร้าง",
    confidenceReason: "อ่านราคาจากบล็อกราคาหลักของหน้าสินค้าได้โดยตรง",
    dealScoreBand: "GOOD_DEAL",
    priceChangePercent: -7.2,
    watchlistIds: ["w-1"],
    timeline: [
      { date: "15 May", price: 10490 },
      { date: "22 May", price: 9790 },
      { date: "29 May", price: 9290 },
      { date: "05 Jun", price: 8990 },
      { date: "11 Jun", price: 8990 },
    ],
  },
  {
    id: "prd-2",
    title: "Samsung 990 EVO Plus 2TB NVMe SSD",
    store: "JIB",
    storeKey: "jib",
    category: "Storage",
    imageUrl: "https://images.unsplash.com/photo-1591799265444-d66432b91588?auto=format&fit=crop&w=1200&q=80",
    sourceUrl: "https://www.jib.co.th/web/product/readProduct/68123",
    currentPrice: 4890,
    targetPrice: 4590,
    lowest30d: 4690,
    average30d: 5290,
    lastCheckedAt: "2026-06-11T11:52:00+07:00",
    status: "IN_STOCK",
    confidenceLevel: "HIGH",
    confidenceLabel: "ดึงข้อมูลได้เสถียร",
    confidenceReason: "รูปแบบราคาและ SKU ตรงกันอย่างสม่ำเสมอ",
    dealScoreBand: "BEST_PRICE",
    priceChangePercent: -10.4,
    watchlistIds: ["w-1", "w-2"],
    timeline: [
      { date: "15 May", price: 5490 },
      { date: "22 May", price: 5290 },
      { date: "29 May", price: 5190 },
      { date: "05 Jun", price: 4890 },
      { date: "11 Jun", price: 4890 },
    ],
  },
  {
    id: "prd-3",
    title: "Dyson V12 Detect Slim Fluffy",
    store: "HomePro",
    storeKey: "homepro",
    category: "Home Appliance",
    imageUrl: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
    sourceUrl: "https://www.homepro.co.th/p/1280001",
    currentPrice: 19900,
    targetPrice: 18500,
    lowest30d: 18990,
    average30d: 20550,
    lastCheckedAt: "2026-06-11T10:11:00+07:00",
    status: "IN_STOCK",
    confidenceLevel: "MEDIUM",
    confidenceLabel: "เงื่อนไขจัดส่งไม่ชัดเจน",
    confidenceReason: "ดึงราคาได้สำเร็จ แต่ยังอาจมีเงื่อนไขจัดส่งเพิ่มเติม",
    dealScoreBand: "NORMAL",
    priceChangePercent: -3.2,
    watchlistIds: ["w-2"],
    timeline: [
      { date: "15 May", price: 20990 },
      { date: "22 May", price: 20590 },
      { date: "29 May", price: 19990 },
      { date: "05 Jun", price: 19900 },
      { date: "11 Jun", price: 19900 },
    ],
  },
  {
    id: "prd-4",
    title: "TP-Link Deco XE75 Pro Mesh Wi-Fi 6E",
    store: "Advice",
    storeKey: "advice",
    category: "Networking",
    imageUrl: "https://images.unsplash.com/photo-1647427060118-4911c9821b82?auto=format&fit=crop&w=1200&q=80",
    sourceUrl: "https://www.advice.co.th/product/network/deco-xe75-pro",
    currentPrice: 12990,
    targetPrice: 10990,
    lowest30d: 11990,
    average30d: 13490,
    lastCheckedAt: "2026-06-11T09:33:00+07:00",
    status: "OUT_OF_STOCK",
    confidenceLevel: "LOW",
    confidenceLabel: "ใช้ตัวเลือกสำรอง",
    confidenceReason: "ดึงราคาจาก selector สำรองหลังจากโครงหน้าเว็บไม่ตรงกับตัวหลัก",
    dealScoreBand: "WAIT",
    priceChangePercent: 2.1,
    watchlistIds: [],
    timeline: [
      { date: "15 May", price: 13190 },
      { date: "22 May", price: 13390 },
      { date: "29 May", price: 12990 },
      { date: "05 Jun", price: 12990 },
      { date: "11 Jun", price: 12990 },
    ],
  },
];

export const watchlists: Watchlist[] = [
  {
    id: "w-1",
    name: "อัปเกรดโต๊ะทำงาน",
    description: "รวมจอ SSD และอุปกรณ์ที่คุ้มค่าซื้อเมื่อราคาลงจริง",
    publicId: "battle-station-upgrades",
    itemIds: ["prd-1", "prd-2"],
    isPublic: true,
  },
  {
    id: "w-2",
    name: "รีเฟรชของใช้ในบ้าน",
    description: "รวมเครื่องใช้ไฟฟ้าและอุปกรณ์เครือข่ายสำหรับรอบอัปเกรดครั้งถัดไป",
    publicId: "home-setup-refresh",
    itemIds: ["prd-2", "prd-3"],
    isPublic: false,
  },
];

export const scrapeLogs: ScrapeLog[] = [
  {
    id: "log-1",
    store: "Power Buy",
    url: products[0].sourceUrl,
    success: true,
    message: "จับคู่บล็อกราคาได้และบันทึก snapshot เรียบร้อย",
    responseTimeMs: 1120,
    createdAt: "2026-06-11T12:05:10+07:00",
  },
  {
    id: "log-2",
    store: "Advice",
    url: products[3].sourceUrl,
    success: false,
    message: "ใช้ selector สำรองดึงราคาได้ แต่ไม่พบป้ายสถานะสต็อก",
    responseTimeMs: 1890,
    createdAt: "2026-06-11T09:33:14+07:00",
  },
  {
    id: "log-3",
    store: "HomePro",
    url: products[2].sourceUrl,
    success: true,
    message: "ดึงข้อมูลสำเร็จพร้อมแจ้งเตือนเรื่องเงื่อนไขการจัดส่ง",
    responseTimeMs: 1460,
    createdAt: "2026-06-11T10:11:21+07:00",
  },
];
